name: "Terraform Build"

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    outputs:
      server_ip: ${{ steps.terraform_variable.outputs.server_ip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false 


      - name: Terraform Format
        id: fmt
        run: terraform -chdir=terraform fmt  -check 

      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init 
      
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=terraform validate  -no-color 

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=terraform plan  -no-color -input=false 
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: terraform_apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform  -chdir=terraform apply  -auto-approve -input=false 


      - name: Get Terraform Outputs
        id: terraform_variable 
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          server_ip=$(terraform -chdir=terraform  output -raw server-address)
          
          #echo "server_ip=$(terraform -chdir=terraform  output -raw server-address)" >> $GITHUB_ENV 
          #echo "action_state=yellow" >> $GITHUB_ENV
          #echo "::set-env name=server_ip::$server_ip"
          echo "server_ip=$server_ip" >> $GITHUB_ENV
          echo "::set-output name=server_ip::$server_ip"

     
      - name: Echo Output
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "${{env.server_ip}}" 


  ci: 
    name: "ci"
    needs: [terraform]
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '17'
      - run: echo ${{ needs.terraform.outputs.server_ip }}
      - run: ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.terraform.outputs.server_ip }}
    